# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 612)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputlabel = QtWidgets.QLabel(self.centralwidget)
        self.outputlabel.setGeometry(QtCore.QRect(10, 10, 341, 91))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.outputlabel.setFont(font)
        self.outputlabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputlabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.outputlabel.setLineWidth(2)
        self.outputlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputlabel.setObjectName("outputlabel")
        self.percent_button = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("%"))
        self.percent_button.setGeometry(QtCore.QRect(10, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.percent_button.setFont(font)
        self.percent_button.setObjectName("percent_button")
        self.clear_button = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("C"))
        self.clear_button.setGeometry(QtCore.QRect(100, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.clear_button.setFont(font)
        self.clear_button.setObjectName("clear_button")
        self.arrow_button = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.back_it())
        self.arrow_button.setGeometry(QtCore.QRect(190, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.arrow_button.setFont(font)
        self.arrow_button.setObjectName("arrow_button")
        self.divide_button = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("/"))
        self.divide_button.setGeometry(QtCore.QRect(280, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.divide_button.setFont(font)
        self.divide_button.setObjectName("divide_button")
        self.nine_button = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("9"))
        self.nine_button.setGeometry(QtCore.QRect(190, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.nine_button.setFont(font)
        self.nine_button.setObjectName("nine_button")
        self.eight_button = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("8"))
        self.eight_button.setGeometry(QtCore.QRect(100, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.eight_button.setFont(font)
        self.eight_button.setObjectName("eight_button")
        self.seven_button = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("7"))
        self.seven_button.setGeometry(QtCore.QRect(10, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.seven_button.setFont(font)
        self.seven_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seven_button.setObjectName("seven_button")
        self.multiply_button = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("*"))
        self.multiply_button.setGeometry(QtCore.QRect(280, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.multiply_button.setFont(font)
        self.multiply_button.setObjectName("multiply_button")
        self.six_button = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("6"))
        self.six_button.setGeometry(QtCore.QRect(190, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.six_button.setFont(font)
        self.six_button.setObjectName("six_button")
        self.five_button = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("5"))
        self.five_button.setGeometry(QtCore.QRect(100, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.five_button.setFont(font)
        self.five_button.setObjectName("five_button")
        self.four_button = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("4"))
        self.four_button.setGeometry(QtCore.QRect(10, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.four_button.setFont(font)
        self.four_button.setObjectName("four_button")
        self.subtract_button = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("-"))
        self.subtract_button.setGeometry(QtCore.QRect(280, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.subtract_button.setFont(font)
        self.subtract_button.setObjectName("subtract_button")
        self.three_button = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("3"))
        self.three_button.setGeometry(QtCore.QRect(190, 380, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.three_button.setFont(font)
        self.three_button.setObjectName("three_button")
        self.two_button = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("2"))
        self.two_button.setGeometry(QtCore.QRect(100, 380, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.two_button.setFont(font)
        self.two_button.setObjectName("two_button")
        self.one_button = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("1"))
        self.one_button.setGeometry(QtCore.QRect(10, 380, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.one_button.setFont(font)
        self.one_button.setObjectName("one_button")
        self.add_button = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("+"))
        self.add_button.setGeometry(QtCore.QRect(280, 380, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.add_button.setFont(font)
        self.add_button.setObjectName("add_button")
        self.point_button = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.dot_it())
        self.point_button.setGeometry(QtCore.QRect(190, 470, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.point_button.setFont(font)
        self.point_button.setObjectName("point_button")
        self.zero_button = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("0"))
        self.zero_button.setGeometry(QtCore.QRect(100, 470, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.zero_button.setFont(font)
        self.zero_button.setObjectName("zero_button")
        self.sign_button = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.plus_minus())
        self.sign_button.setGeometry(QtCore.QRect(10, 470, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sign_button.setFont(font)
        self.sign_button.setObjectName("sign_button")
        self.equal_button = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.math_it())
        self.equal_button.setGeometry(QtCore.QRect(280, 470, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.equal_button.setFont(font)
        self.equal_button.setObjectName("equal_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def back_it(self):
        if (len(self.outputlabel.text())==1):
            self.outputlabel.setText("0")
        else:
            st = self.outputlabel.text()
            str = st[:len(st)-1]
            self.outputlabel.setText(str)
    def math_it(self):
        screen = self.outputlabel.text()
        try:
            answer = eval(screen)
            self.outputlabel.setText(f"{str("%.6f" % answer)}")
        except:
            self.outputlabel.setText("Error")
    def plus_minus(self):
        screen = self.outputlabel.text()
        if (screen[0]=="-"):
            screen = screen[1:]
            self.outputlabel.setText(screen)
        elif (screen[0]!="0"):
            screen = "-"+screen
            self.outputlabel.setText(screen)
    def dot_it(self):
        screen = self.outputlabel.text()
        count_dot = 0
        count_operand = 0
        for char in screen:
            if (char=='.'):
                count_dot = count_dot+1
            elif (char=='+' or char=='/' or char=='*' or char=='-'):
                count_operand = count_operand+1
        if (count_dot==count_operand and (screen[-1]!='+' and screen[-1]!='-' and screen[-1]!='*' and screen[-1]!='/')):
            self.outputlabel.setText(f"{screen}.")
            
    def press_it(self, pressed):
        if (pressed=="C"):
            self.outputlabel.setText("0")
        else:
            if (self.outputlabel.text()=="0"):
                self.outputlabel.setText("")
            self.outputlabel.setText(f"{self.outputlabel.text()}{pressed}")
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.outputlabel.setText(_translate("MainWindow", "0"))
        self.percent_button.setText(_translate("MainWindow", "%"))
        self.clear_button.setText(_translate("MainWindow", "C"))
        self.arrow_button.setText(_translate("MainWindow", "<<"))
        self.divide_button.setText(_translate("MainWindow", "/"))
        self.nine_button.setText(_translate("MainWindow", "9"))
        self.eight_button.setText(_translate("MainWindow", "8"))
        self.seven_button.setText(_translate("MainWindow", "7"))
        self.multiply_button.setText(_translate("MainWindow", "x"))
        self.six_button.setText(_translate("MainWindow", "6"))
        self.five_button.setText(_translate("MainWindow", "5"))
        self.four_button.setText(_translate("MainWindow", "4"))
        self.subtract_button.setText(_translate("MainWindow", "-"))
        self.three_button.setText(_translate("MainWindow", "3"))
        self.two_button.setText(_translate("MainWindow", "2"))
        self.one_button.setText(_translate("MainWindow", "1"))
        self.add_button.setText(_translate("MainWindow", "+"))
        self.point_button.setText(_translate("MainWindow", "."))
        self.zero_button.setText(_translate("MainWindow", "0"))
        self.sign_button.setText(_translate("MainWindow", "+/-"))
        self.equal_button.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
