# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todo.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 612)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.additem_pushbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.addit())
        self.additem_pushbutton.setGeometry(QtCore.QRect(20, 70, 250, 50))
        self.additem_pushbutton.setObjectName("additem_pushbutton")
        self.deleteitem_pushbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.deleteit())
        self.deleteitem_pushbutton.setGeometry(QtCore.QRect(280, 70, 250, 50))
        self.deleteitem_pushbutton.setObjectName("deleteitem_pushbutton")
        self.clearall_pushbutton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.clearit())
        self.clearall_pushbutton.setGeometry(QtCore.QRect(540, 70, 251, 50))
        self.clearall_pushbutton.setObjectName("clearall_pushbutton")
        self.Additem_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Additem_LineEdit.setGeometry(QtCore.QRect(20, 10, 771, 51))
        self.Additem_LineEdit.setObjectName("Additem_LineEdit")
        self.mylist_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.mylist_listWidget.setGeometry(QtCore.QRect(20, 131, 771, 421))
        self.mylist_listWidget.setObjectName("mylist_listWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 814, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def addit(self):
        # Get item from LineEdit 
        item = self.Additem_LineEdit.text()

        # Add item to list widget
        self.mylist_listWidget.addItem(item)

        # Clear the LineEdit
        self.Additem_LineEdit.setText("")
    def deleteit(self):
        # Grab the selected row or current row
        clicked = self.mylist_listWidget.currentRow()
        # Delete selected row
        self.mylist_listWidget.takeItem(clicked)
    def clearit(self):
        self.mylist_listWidget.clear()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "To Do List"))
        self.additem_pushbutton.setText(_translate("MainWindow", "Add Item to List"))
        self.deleteitem_pushbutton.setText(_translate("MainWindow", "Delete Item From List"))
        self.clearall_pushbutton.setText(_translate("MainWindow", "Clear The List"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
