# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Second_Window(object):
    def setupUi(self, Second_Window):
        Second_Window.setObjectName("Second_Window")
        Second_Window.resize(614, 327)
        self.centralwidget = QtWidgets.QWidget(Second_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 50, 431, 141))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        Second_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Second_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 614, 26))
        self.menubar.setObjectName("menubar")
        Second_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Second_Window)
        self.statusbar.setObjectName("statusbar")
        Second_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Second_Window)
        QtCore.QMetaObject.connectSlotsByName(Second_Window)

    def retranslateUi(self, Second_Window):
        _translate = QtCore.QCoreApplication.translate
        Second_Window.setWindowTitle(_translate("Second_Window", "MainWindow"))
        self.label.setText(_translate("Second_Window", "Second Window!!!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Second_Window = QtWidgets.QMainWindow()
    ui = Ui_Second_Window()
    ui.setupUi(Second_Window)
    Second_Window.show()
    sys.exit(app.exec_())
